version: '2.2'

services:
    bemodule:
      container_name: searchengine.budgetcontrol.lan
      image: mlabfactory/php8-apache:v1.0
      volumes:
        - ./:/var/www/workdir
      networks:
        - budgetcontrol_network
      restart: unless-stopped

networks:
  budgetcontrol_network:
    external: false
    name: budgetcontrol_network
