name: Deploy application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: dev
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 1
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            extensions: curl, json, mbstring, zip
            tools: composer
            
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Install Composer dependencies
          run: composer install --no-dev --optimize-autoloader
          
        - name: Install Serverless Framework
          run: npm install -g serverless
          
        - name: Deploy to AWS Lambda
          run: serverless deploy --stage prod --verbose
